title: Rokaki
description: A DSL for filtering data in web requests (ActiveRecord)
# For project pages (https://<user>.github.io/<repo>), set:
#   url: "https://tevio.github.io"
#   baseurl: "/rokaki"
# This ensures theme assets like /assets/main.css resolve under /rokaki/ on GitHub Pages.
baseurl: "/rokaki"
url: "https://tevio.github.io"

theme: minima
plugins:
  - jekyll-polyglot

# Internationalization (jekyll-polyglot)
languages:
  - en
  - ja
  - zh-CN
  - zh-TW
  - es
  - pt-BR
  - ru
  - fr
  - de
  - ko
  - it
  - tr
  - pl
  - nl
  - id
  - vi
  - uk
  - ar
  - he
  - hi
default_lang: en
rtl_locales: ["ar", "he"]
exclude_from_localization:
  - doc/
  - pkg/
  - spec/
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - rokaki.gemspec
  - Guardfile
  - README.md

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Exclude existing generated RDoc folder from site
exclude:
  - doc/
  - pkg/
  - spec/
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - rokaki.gemspec
  - Guardfile
  - README.md
