title: Rokaki
description: A DSL for filtering data in web requests (ActiveRecord)
# For project pages (https://<user>.github.io/<repo>), set:
#   url: "https://tevio.github.io"
#   baseurl: "/rokaki"
# This ensures theme assets like /assets/main.css resolve under /rokaki/ on GitHub Pages.
baseurl: "/rokaki"
url: "https://tevio.github.io"
theme: minima

# Limit header navigation to these pages to avoid top-level Oracle link
header_pages:
  - index.md
  - usage.md
  - dsl_syntax.md
  - adapters.md
  - configuration.md

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Exclude existing generated RDoc folder from site
exclude:
  - doc/
  - pkg/
  - spec/
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - rokaki.gemspec
  - Guardfile
  - README.md
