name: Run Oracle RSpec tests

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  oracle-specs:
    runs-on: ubuntu-latest
    services:
      oracle:
        image: gvenzl/oracle-free:23-slim
        env:
          ORACLE_PASSWORD: oracle
        ports:
          - 1521:1521
        options: >-
          --health-cmd "bash -lc 'echo exit | sqlplus -L -s sys/oracle@//localhost:1521/FREEPDB1 as sysdba'"
          --health-interval 15s --health-timeout 10s --health-retries 40

    env:
      ORACLE_HOST: localhost
      ORACLE_PORT: 1521
      ORACLE_DATABASE: /freepdb1
      ORACLE_USERNAME: ROKAKI
      ORACLE_PASSWORD: rokaki
      ORACLE_ENABLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip libaio1 build-essential pkg-config

      - name: Install Oracle Instant Client (Basic + SDK)
        run: |
          IC_DIR=/opt/oracle/instantclient_23_3
          sudo mkdir -p /opt/oracle
          cd /opt/oracle
          # Download Instant Client 23.3 (public links)
          wget -q https://download.oracle.com/otn_software/linux/instantclient/233000/instantclient-basiclite-linux.x64-23.3.0.23.09.zip
          wget -q https://download.oracle.com/otn_software/linux/instantclient/233000/instantclient-sdk-linux.x64-23.3.0.23.09.zip
          sudo unzip -q instantclient-basiclite-linux.x64-23.3.0.23.09.zip
          sudo unzip -q instantclient-sdk-linux.x64-23.3.0.23.09.zip
          # Normalize path name to instantclient_23_3
          sudo mv instantclient_23_3 $IC_DIR || true
          if [ ! -d "$IC_DIR" ]; then
            # If unzip created a different name, detect and move
            found=$(ls -d /opt/oracle/instantclient_* | head -n1)
            sudo mv "$found" "$IC_DIR"
          fi
          # Ensure lib symlink folder exists for search paths
          sudo mkdir -p "$IC_DIR/lib"
          cd "$IC_DIR/lib"
          for f in libclntsh.dylib libclntsh.so.23.1 libclntsh.so libocci.so.23.1 libocci.so libnnz.so; do
            [ -e "$f" ] || [ -e "../$f" ] && sudo ln -sf ../$f $f || true
          done
          echo "OCI_DIR=$IC_DIR" | sudo tee -a /etc/environment
          echo "OCI_LIB_DIR=$IC_DIR" | sudo tee -a /etc/environment
          echo "OCI_INC_DIR=$IC_DIR/sdk/include" | sudo tee -a /etc/environment
          echo "DYLD_FALLBACK_LIBRARY_PATH=$IC_DIR:$IC_DIR/lib" | sudo tee -a /etc/environment

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: false

      - name: Bundle install with Oracle build flags
        env:
          WITH_ORACLE: "1"
          OCI_DIR: /opt/oracle/instantclient_23_3
          OCI_LIB_DIR: /opt/oracle/instantclient_23_3
          OCI_INC_DIR: /opt/oracle/instantclient_23_3/sdk/include
          DYLD_FALLBACK_LIBRARY_PATH: /opt/oracle/instantclient_23_3:/opt/oracle/instantclient_23_3/lib
        run: |
          bundle config set --local build.ruby-oci8 "--with-instant-client-dir=$OCI_DIR --with-instant-client-include=$OCI_INC_DIR --with-instant-client-lib=$OCI_LIB_DIR"
          bundle install --jobs 4 --retry 3

      - name: Wait for Oracle to be ready and create test user/schema
        run: |
          # Wait for listener
          for i in {1..60}; do
            nc -z 127.0.0.1 1521 && echo "Oracle listener up" && break || sleep 2
          done
          # Create test user on PDB FREEPDB1
          docker exec -i oracle-free bash -lc "sqlplus -s sys/oracle@//localhost:1521/FREEPDB1 as sysdba <<'SQL'\nWHENEVER SQLERROR EXIT SQL.SQLCODE;\nALTER SESSION SET CONTAINER = FREEPDB1;\nDECLARE v_exists NUMBER; BEGIN SELECT COUNT(*) INTO v_exists FROM dba_users WHERE username = 'ROKAKI'; IF v_exists = 0 THEN EXECUTE IMMEDIATE 'CREATE USER ROKAKI IDENTIFIED BY rokaki'; EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO ROKAKI'; EXECUTE IMMEDIATE 'ALTER USER ROKAKI QUOTA UNLIMITED ON USERS'; END IF; END; /\nEXIT\nSQL"

      - name: Run Oracle specs
        env:
          ORACLE_HOST: localhost
          ORACLE_PORT: 1521
          ORACLE_DATABASE: /freepdb1
          ORACLE_USERNAME: ROKAKI
          ORACLE_PASSWORD: rokaki
          ORACLE_ENABLED: "1"
          DYLD_FALLBACK_LIBRARY_PATH: /opt/oracle/instantclient_23_3:/opt/oracle/instantclient_23_3/lib
        run: |
          bundle exec rspec spec/lib/04_oracle_aware_spec.rb
