name: Build documentation (pre deploy)

on:
  push:
    branches: [ main, master, pages ]
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: docs/Gemfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - name: Build site
        run: |
          bundle exec jekyll build -s docs -d _site

      - name: Upload built site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
