name: Run RSpec tests
on: [push]
jobs:
  run-rspec-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:9.4
        env:
          MYSQL_DATABASE: rokaki
          MYSQL_USER: rokaki
          MYSQL_PASSWORD: rokaki
          MYSQL_ROOT_PASSWORD: rokaki
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: rokaki
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "5QL5£rv£r"
        ports:
          - 1433:1433
        # No built-in healthcheck; we'll wait in a step using nc

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpq-dev default-libmysqlclient-dev freetds-dev netcat-openbsd

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 3.3.0
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Wait for databases to be ready
        shell: bash
        run: |
          for i in {1..60}; do
            nc -z 127.0.0.1 3306 && echo "MySQL up" && break || sleep 1
          done
          for i in {1..60}; do
            nc -z 127.0.0.1 5432 && echo "Postgres up" && break || sleep 1
          done
          for i in {1..120}; do
            nc -z 127.0.0.1 1433 && echo "SQL Server up" && break || sleep 1
          done

      - name: Run tests
        run: |
          ./spec/ordered_run.sh
